version: "3.9"
services:
  api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports: 
      - 127.0.0.1:3333:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "express_mysql_sequelize_development"
    tty: true